### PR TITLE
makesms updates

### PR DESCRIPTION
**Pull request by raphnet**
- Add a feature to merge external data into the ROM before computing the checksum. (-mbin and -mbank, taking values in bytes and banks respectively)
 - Add an option to change the default value for unused ROM. (-emptyfill)
 - Add a makefile
 - Add a full usage message.

### CODE REVIEW

**Comment by raphnet** [comment]
Here is the use case in case you ask.

I needed to integrate a large (spawning several banks) self-contained program coded in assembly (with WLADX) into my project which is coded in C (mostly) using devkitSMS. My assembly program requires a small chunk of support code placed in bank0 at a specific address, otherwise it is compiled to occupy upper banks (past the last bank used by the "normal" part of my devkitSMS project).

One solution I came up with was copying parts of the assembly program compiled assembly.SMS file over the .SMS obtained from the C project using makesms. However the checksum would then be invalid. I could have made a separate path tool with checksum fixup, but it felt easier to just extend makesms to support reading data from sources in addition to the usual .ihx file.

```makesms -pp -mbin logo/animation.sms:0x3F40:64:0x3F40 -mbank logo/animation.sms:16:8:16 $< $@```

Above, I am copying the 64 byte support code residing at 0x3F40 over empty space using the -mbin option. Then, I use the -mbank option to copy 8 banks from the 16th bank in the source .sms file over empty space beginning at bank 16 in the final ROM.

I think this can be useful to add a large chunk of data starting at a known bank at the end of the ROM without going through assets2banks and the linker. Of course this can be dangerous so you must know what you are doing. But the code that merges the external data does check if it is writing over bytes that are not to the default value.

**Comment by sverx** [comment]
OK I really didn't imagine one would need to embed code from a separate binary... after all you can code inline asm with SDCC so I suspect there's not that much request for that... but I have nothing against adding something of this kind.

I'm just curious how do you pick a good destination address for your `-mbin` copy... did you simply get backward from $4000 leaving the space for the SDSC and SEGA headers?

**Comment by raphnet** [comment]
Inline asm with SDCC? But then I would not have access to the .bank X slot X directive and there would be no bank() built-in function which I rely on. This assembly code switches banks in slot 1 and 2 a lot so loosing this would make things difficult... And if I understand correctly, I would also be forced to split the source in many parts, compile to a bunch of .rels and then link... So that's why I did not feel inclined to use inline asm with sdcc.

As for the `-mbin` destination, well my project uses banked code and I already placed the SDSC/SEGA headers at the end of the first 16kB. As I am already careful only to add what is necessary to bank 0 to avoid overwriting those headers, there is a lot of free space at the end. So I simply picked an address that came close to the headers.

For safety (or perceived safety) I do have this somewhere, in hope that if I ever add too much code to bank0 and it overlaps with this, there will be an error, but I'm not sure if this works. However the "empty" check I put in makesms should catch the overlap otherwise...
const __at (0x3f40) unsigned char supportcode[64] = { 0xFF ... }

**Comment by sverx** [comment]
> Inline asm with SDCC? But then I would not have access to the .bank X slot X directive and there would be no bank() built-in function which I rely on.

I meant for the small part you needed to sit in bank 0. That code is very short if I understand correctly and if you also need it to stay at a specific address I think there's SDCC support for it (simply `__at(address)` maybe?) though I never checked myself.

Anyway I have no reason not to accept this PR, I am just very curious about the reasons behind all this :smile:

**Comment by raphnet** [comment]
Ah you are right, I could probably embed only the small piece of code using inline assembly somehow, but I like the current -mbin approach because that code has not stabilized yet. So it's easier to keep in sync that way (Workflow is: Tool produces the standalone .sms file, then the main project coded with devkitSMS imports the code/data from the standalone .sms file). I know it's weird and unusual...

Let me know if you would like me to update anything in this pull request.

**Comment by sverx** [comment]
No, it's fine!

**Pull request merged**
