### PR TITLE
Add Paddle controller support

### PR DESCRIPTION
**Pull request by raphnet**

### CODE REVIEW

**Comment by raphnet** [comment]
Paddle Control support was put together with the help of this page:
https://www.smspower.org/Development/Paddle

And also using my own research m aking a homemade paddle:
https://www.raphnet.net/electronique/sms_paddle/index_en.php

Both ports and two paddle types (original and homemade), tested and confirmed to work on a Japanese SMS.

**Comment by raphnet** [comment]
void SMS_paddleInit(void)
{
	port3F = 0x55;
}

I would like to explain why this function exists. In fact a Paddle Control should not need this, it only uses input pins that should already be configured properly. (on hardware where this applies, I've read that japanese consoles do not even have port 3F) 

However, in Meka, unless port 3F holds a value of 0x55, the paddle is not emulated. I think the code in official games try to communicate with an export paddle (which uses an output pin) and therefore set 3F to 0x55 first, but leave the port as-is afterwards. Of course, the "correct" solution would be to fix Meka (I actually intend to do something about this, there are other issues) but meanwhile, I had rather have a ROM that would work out of the box in Meka.

**Comment by sverx** [comment]
Thanks for this, I merged it to a separate branch and I'll work on its integration whenever I get enough time.

> However, in Meka, unless port 3F holds a value of 0x55, the paddle is not emulated. I think the code in official games try to communicate with an export paddle (which uses an output pin) and therefore set 3F to 0x55 first, but leave the port as-is afterwards. Of course, the "correct" solution would be to fix Meka (I actually intend to do something about this, there are other issues) but meanwhile, I had rather have a ROM that would work out of the box in Meka.

I guess the workaround is to set MEKA to Japan (Machine > Region > Japan) so that it emulates a Japanese paddle instead of the (non existent) export paddle.

**Comment by raphnet** [comment]
Hmm, this workaround does not seem to work. The code in inputs.cpp (lines 386 to 434) will only emulate a Japanese paddle if port 3F contains 0x55. But I sent a pull request that makes it work.

**Pull request merged**
