### PR TITLE
Add support for the keyboard of the SC-3000(H) and SK-1100

### PR DESCRIPTION
**Pull request by amoibos**
Detecting mutiple keys simultaneously and encode in the returned key code the row and value of the pressed key. 
Tested with MEKA 0.80-alpha(2023-08-26).

Python snippet to decode the value:
`val=26624; int(bin(val)[:-12][2:].rjust(4,'0'),2), bin(val)[-12:]`

### CODE REVIEW

**Comment by sverx** [comment]
Thank you for this, it can be quite useful. I remember I once thought about using this approach too, it's quite effective. :+1: 

May I ask you to rename the function as `SG_getKeycodes` (with a lowercase 'g') for consistency with other function names?

Also I think the SDCC compiler might generate better code if you move `unsigned int keyb_stat, row_no;` inside the (outer) `for` loop, because those variables don't need to exist outside of that loop. Likely a minor optimization but we'll gladly take that :smiley:

**Comment by sverx** [comment]
@amoibos did you miss my reply? :sweat_smile:

**Review by amoibos — COMMENTED** [review]
I have integrated your feedback.

**Comment by sverx** [comment]
Thank you for your contribution! :smiley:

**Pull request merged**
