### PR TITLE
Implement SMS_readVRAM

### PR DESCRIPTION
**Pull request by raphnet**
Basically SMS_VRAMmemcpy but working in the opposite direction (reads VRAM, writes to RAM)

### CODE REVIEW

**Comment by sverx** [comment]
Well, you might not believe this but I thought about adding the same function this morning.
Lucky me, I was lazy and didn't coded it myself already :stuck_out_tongue: so this is very appreciated :smile: 

Please add cycle counts as comments in asm code when accessing VRAM.

Also, what about making SMS_saveTileMapArea() use this too? I think it might improve speed in almost any case...

**Comment by raphnet** [comment]
For info, my use case is that I need to read back a tile from VRAM to build a new tile (object + background) dynamically at runtime. I could not easily read the tile data from the source in ROM, since I want to store this with PSG compression. But VRAM always has uncompressed data, and now I can access it with this function. 

It's of course slower than reading from RAM, but I suspect that the alternative of implementing random access, possibly with an index, would be even slower anyway.

**Comment by raphnet** [comment]
Ha, you commented as I was writing my comment.

Yes, I'll add the cycle count and see to updating SMS_saveTileMapArea()

**Comment by raphnet** [comment]
Ok, it's done! The new SMS_saveTileMapArea() implementation did not break anything in my project. Not tested on real hardware yet, but everything works in emulicious.

**Comment by sverx** [comment]
Good! :heart: 

Please use `#_VDPControlPort` instead of `#$bf` (and `#_VDPDataPort` instead of `#$be` in `SMS_getTile()` also...)

:bow:

**Comment by sverx** [comment]
I went back to this part this morning and I realized that `SMS_getTile(void)` won't work correctly by its own because devkitSMS didn't provide a way to set the VDP address for reading.

So I think I will change that into `SMS_getTile(x,y)`.

If one needs to read more than a single tile they will use `SMS_readVRAM` or `SMS_saveTileMapArea()`.

Or am I missing something here? :thinking:

**Comment by raphnet** [comment]
SMS_getTile(void) is a leftover from my first implementation of SMS_saveTileMapArea which used SMS_getTile(void). It also relied on a  SMS_PNTAddress_r macro which got removed afterwards, and in the end I rewrote SMS_saveTileMapArea to use SMS_readVRAM() instead, which leaves us with this SMS_getTile(void) which is not very useful on its own as you point out.

My personal preference would be to leave SMS_getTile(void) as is, to let it mirror how SMS_setTile works, but then also add an opposite to SMS_setNextTileatXY dedicated for reading, perhaps called SMS_readNextTileFrom(x,y). 

I think it can be convenient being able to call SMS_getTile(void) to read consecutive locations in certain situations. Passing an address or x/y coordinate for each single read in such cases is not necessary.

Of course, also having SMS_getTileatXY(x,y) would be handy when a single location is to be accessed.

**Comment by sverx** [comment]
`SMS_readNextTileFrom(x,y)` is actually a very good idea and `SMS_getTileatXY(x,y)` could be a macro working similarly to `SMS_setTileatXY(x,y)` but for reading a tile, of course.

I will work on it, thanks! :+1:

**Comment by raphnet** [comment]
I believe the comma operator can be used here, since the value and type to be returned is that of the second function call. So possibly something like this?

`#define SMS_getTileatXY(x,y) ( SMS_readNextTileFrom(x,y) , SMS_getTile()  )`

**Comment by sverx** [comment]
I admit I never used the comma operator. Let me check that...

**Comment by sverx** [comment]
OK, seems to work as expected! :+1: 

Thanks!

**Pull request merged**
