### PR TITLE
Add palette color addition logic

### PR DESCRIPTION
**Pull request by mikehdt**
Per [this discussion](https://www.smspower.org/forums/15228-DevkitSMSDevelopYourHomebrewInC?start=600#129119) on SMSpower, this adds logic for the inverse of the palette colour subtraction.

An example use might be something like:
```
const unsigned char color_increase_in[9] = {RGB(1, 0, 0), RGB(1, 1, 0), RGB(1, 1, 1),
                                            RGB(2, 1, 1), RGB(2, 2, 1), RGB(2, 2, 2),
                                            RGB(3, 2, 2), RGB(3, 3, 2), RGB(3, 3, 3)};

void fade_to_white(unsigned char palette[16], unsigned char step)
{
    for (int i = 0; i < 10; i++) {
        SMS_waitForVBlank();
        loadBGPaletteafterColorAddition(palette, color_increase_in[i]);
    }
}
```

I **think** I've got it as it should be, but I'm certainly no C expert 😂 Happy to make any changes as need be.

Note: the `a` in after is lowercase, only as the existing subtraction function code was that way. If it makes sense to change them both to `...PaletteAfterColor...` then that's doable of course.

Edit: Might need to also recompile. I didn't manage to get the building part going (but I did test the logic in a separate codebase), so might need some assistance there.

### CODE REVIEW

**Comment by sverx** [comment]
Thanks for your contribution. I'll merge into master later :+1:

**Comment by sverx** [comment]
It's now into master.

One note though - when you use a _#define_ with parameters, **each one** the parameters **needs** to be put in brackets, as in:

`#define DOUBLE(n)  ( (n) * 2 )` 

otherwise see would happen here if you _don't_ do it and your code then calls `DOUBLE(5+3);` ...

**Comment by mikehdt** [comment]
Ahh, I see what you mean. C isn't my primary dev language, good to know. Thanks for reviewing / merging! Hope that people find it useful 😄

**Comment by sverx** [comment]
No worries, it's a common pitfall for everyone that's not experienced with C, and often also for those who are :wink: 

The reason behind why is so, is that `#define` is a _preprocessor_ directive, and the _preprocessor_ is basically just a text editor that does search&replace on your C source.

Also, I'm sure somebody will find these functions useful :heart:

**Pull request merged**
