### PR TITLE
Add a Makefile for building SMSlib.

### PR DESCRIPTION
**Pull request by raphnet**
Also comments a few build options which can be easily enabled
enabled by uncommenting the corresponding line in the Makefile.

### CODE REVIEW

**Comment by raphnet** [comment]
Here is some additional info. 

I tried to reproduce exactly how the batch file "how to build this.txt" (ps: Why not rename it to compile.bat?) builds the library, but there is one difference.

In the Makefile, the following files are compiled with "--peep-file peep-rules.txt --peep-asm" but in the batch file, those are not:

SMSlib_zx7.c
SMSlib_UNSAFE_zx7.c
SMSlib_aPLib.c
SMSlib_paddle.c

Is this simply an omission, or is there a reason for compiling those with different arguments? I can update the Makefile to fix this if necessary.

**Comment by raphnet** [comment]
Also, it should be noted that I only tested the SMS version of the generated build, not the Game Gear version yet..

**Comment by sverx** [comment]
`--peep-file peep-rules.txt` might not be needed in some cases, but I seem to remember it won't cause troubles if used everywhere
`--peep-asm` instead could actually screw handwritten asm code timing so it's better leave that out in some cases.

**Comment by raphnet** [comment]
Thank you, I updated the makefile to avoid compiling the discussed files with --peep-asm and pushed my changes.

Now in an attempt to be 100% sure that my build is correct, I extracted the .rel files form the binary distribution (SMSlib.lib) to compare with those from my build, but about half of the files differ... So I was wondering, could you tell me which version of sdcc you use to compile?

**Comment by sverx** [comment]
I suspect it's hard to match the generated rels byte to byte even if using the same version...
anyway the released libs are compiled using version 4.0.7 (snapshot #12035)
finally, I'm also using the command line switch `--max-allocs-per-node 100000` to improve code generation a bit

**Comment by raphnet** [comment]
Indeed, even with the 4.0.7 snapshot there are differences in the resulting binaries. But I'm not sure if the files in SMSlib.lib were built exactly with the current source code... I will try again with 4.1.0.

**Comment by sverx** [comment]
> I'm not sure if the files in SMSlib.lib were built exactly with the current source code

They should!

**Comment by raphnet** [comment]
There were a few files that were compiled with --peep-asm in my Makefile that shouldn't which I had missed. I can confirm that for SMSlib_STMcomp.c --peep-asm definitely broke things!

So with this corrected, the remaining differing files are as follows. I have compared the sdcc options from "how to build this.txt" to my build and those differences are not a result of incorrect options. It's possibly just a compiler version issue.

- Distributed lib file:
e811f4b86341c788041ec6f0ab7b4ebc  SMSlib_loadTileMapArea.rel
8b1d0210d08c688fdd0290e60bbe027f  SMSlib.rel
5b0378cfabea46ad4cceb41dcc1353fb  SMSlib_spriteAdv.rel
734377c09d5f8446b636cb4a843c4316  SMSlib_spriteClip.rel
f8aad3e03c437a1d6c4f86f456d40c72  SMSlib_sprite.rel
3a03a29a40de3b2d05e0833d215529c3  SMSlib_VRAMmemset.rel
(Also, only in the distributed .lib: SMSlib_loadTiles.rel)


- My build with sdcc 4.1.0 #12072:
29eb1b7b6ff393fcbe5fc0d4ff7f308f  SMSlib_loadTileMapArea.rel
a94e5047c732df7f37b4f1c514ca8912  SMSlib.rel
e8dccc25c9711cc713cce46049c14159  SMSlib_spriteAdv.rel
3adb593496979ccfed3ad7cc2e5690ad  SMSlib_spriteClip.rel
28b46a705db6615c0e6065d0742b6b18  SMSlib_sprite.rel
435efdf58ec7195c79aedc15d7c59081  SMSlib_VRAMmemset.rel

**Comment by sverx** [comment]
I should probably switch to sdcc 4.1.0 (#12072) too and see what happens...

**Comment by sverx** [comment]
I have switched to sdcc 4.1.0  (#12072) in the sdcccall_1 branch https://github.com/sverx/devkitSMS/tree/sdcccall_1
Try comparing with that, thanks!

**Comment by raphnet** [comment]
Thank you for the update! I compared with the lib in the sdcccall_1 branch. Those two files are now identical to my build (using my Makefile and sdcc 4.1.0 #12072)

SMSlib_sprite.rel
SMSlib_VRAMmemset.rel

But the four other files previously mentioned were still different. After looking more closely, I noticed that I was passing a value of 1000000 instead of 100000 to --max-allocs-per-node. I recompiled with the correct value and the situation changed. Non-matching files were now:

3459b3dcfe506d83456e35f930570c8d  SMSlib_load1bppTiles.rel
d68a6a25e2ff1923f9f7766b5c8078b4  SMSlib_loadTileMapArea.rel
a94e5047c732df7f37b4f1c514ca8912  SMSlib.rel
e8dccc25c9711cc713cce46049c14159  SMSlib_spriteAdv.rel
3adb593496979ccfed3ad7cc2e5690ad  SMSlib_spriteClip.rel

Strange... I looked very closely to "How to build this.txt" and could not find anything different with my Makefile. On a hunch I tried commenting the --max-allocs-per-node in my makefile, which led to only one remaining non-matching file: SMSlib.rel.

Distributed binary (in sdcccall_1 branch)
222b4dbfa8ef123efbbc00f550aa240b  SMSlib.rel

My build:
a94e5047c732df7f37b4f1c514ca8912  SMSlib.rel

Compiling SMSlib.c without the --reserve-regs-iy finally yielded a .rel identical to your sdcccall_1 build!. Finally. (But I suspect the build may have issues without the --reserve-regs-iy here, I did not try using)

So I have some questions about how you build the library. Do you run "How to build this.txt" as a batch file? Or do you have a separate script/batch file that's not part of the repo?

By the way, I was also surprised to find that SMSlib_loadTiles.rel was still present in your latest library build. I suspect this could happen if you did not erase the old .lib before building (i.e. I think sdar would then just leave alone the SMSlib_loadTiles.rel file in the archive)

**Comment by sverx** [comment]
Yes, I'm using a different script because I'm also compiling each source file using different possible defines to make sure everything works. But really I don't get why you should get different binaries using the same sources and commands.

Anyway you're right I didn't delete the old .lib files. I never realized sdar would replace/append modules if the file was already existing. I will start by deleting the lib files and recompile... and then I'll see if I can find why we still don't have a 100% match on the binaries. I have no clue at the moment.

**Comment by raphnet** [comment]
Well this explains everything then. I just rebuilt using the --max-allocs-per-node switch only and I can confirm that all the files in the SMS build match now.

I also checked the GG build more closely and corrected an error in my Makefile (missing objects in the lib) and there is one last issue I have with the SMSlib_spriteClip game gear version.

My build:
28b46a705db6615c0e6065d0742b6b18  SMSlib_spriteClip_GG.rel

Build from the sdcccall_1 branch:
3f352b4e2dae1b1fc59aa5a5ef89b45c  SMSlib_spriteClip_GG.rel

Here is the exact command I used to compile this file:
`sdcc -mz80 --max-allocs-per-node 100000  --peep-file peep-rules.txt --peep-asm -c -o SMSlib_spriteClip_GG.rel SMSlib_sprite.c -DTARGET_GG`

I tried removing --max-allocs-per-node and the --peep options, but the md5 of the resulting file never changed...

**Comment by raphnet** [comment]
Nevermind, I found my mistake and the last update corrects the problem. (I was compiling SMSlib_sprite.c into SMSlib_spriteClip_GG.rel)  :facepalm:

**Comment by sverx** [comment]
So they all match now?

**Comment by raphnet** [comment]
Yes, all the files now match, SMS and GG versions.

**Comment by sverx** [comment]
Wonderful, thanks! :+1: 
Merged!

**Pull request merged**
